export interface ITripVehicleResponse {
  id: string;
  vehicle: {
    id: string;
    plate: string;
    model: string;
    brand: string;
    capacity: number;
    category: string;
  };
  primaryDriver: {
    id: string;
    name: string;
    licenseNumber: string;
  };
  secondaryDriver?: {
    id: string;
    name: string;
    licenseNumber: string;
  };
  isActive: boolean;
  observations?: string;
}

export interface ITripResponse {
  id: string;
  route: {
    id: string;
    name: string;
    description: string;
  };
  departureTime: Date;
  estimatedArrivalTime: Date;
  actualDepartureTime?: Date;
  actualArrivalTime?: Date;
  status: 'scheduled' | 'in_progress' | 'completed' | 'cancelled' | 'delayed';
  basePrice: number;
  totalSeats: number;
  availableSeats: number;
  isAutoGenerated?: boolean;
  observations?: string;
  vehicles: ITripVehicleResponse[];
  ticketCount: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface ITripFilters {
  routeId?: string;
  status?: string;
  dateFrom?: Date;
  dateTo?: Date;
}
